// Code generated by ent, DO NOT EDIT.

package ent

import (
	"1li/ent/record"
	"1li/ent/schema"
	"1li/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	recordFields := schema.Record{}.Fields()
	_ = recordFields
	// recordDescCode is the schema descriptor for code field.
	recordDescCode := recordFields[0].Descriptor()
	// record.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	record.CodeValidator = recordDescCode.Validators[0].(func(string) error)
	// recordDescTarget is the schema descriptor for target field.
	recordDescTarget := recordFields[1].Descriptor()
	// record.TargetValidator is a validator for the "target" field. It is called by the builders before save.
	record.TargetValidator = recordDescTarget.Validators[0].(func(string) error)
	// recordDescCreatedAt is the schema descriptor for created_at field.
	recordDescCreatedAt := recordFields[2].Descriptor()
	// record.DefaultCreatedAt holds the default value on creation for the created_at field.
	record.DefaultCreatedAt = recordDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescCustomCode is the schema descriptor for customCode field.
	userDescCustomCode := userFields[2].Descriptor()
	// user.DefaultCustomCode holds the default value on creation for the customCode field.
	user.DefaultCustomCode = userDescCustomCode.Default.(bool)
	// userDescAdmin is the schema descriptor for admin field.
	userDescAdmin := userFields[3].Descriptor()
	// user.DefaultAdmin holds the default value on creation for the admin field.
	user.DefaultAdmin = userDescAdmin.Default.(bool)
	// userDescReadAll is the schema descriptor for readAll field.
	userDescReadAll := userFields[4].Descriptor()
	// user.DefaultReadAll holds the default value on creation for the readAll field.
	user.DefaultReadAll = userDescReadAll.Default.(bool)
}
